name: RuralMC
main: com.ruralmc.plugin.RuralMC
version: 1.12.1.46-DEV
author: Chaka
commands:
  rmc:
    description: This is the main RMC command.
    usage: /<command>
  claim:
    description: Claim a chunk
    usage: /<command>
  points:
    description: Points things
    usage: /<command>
  addpoints:
    description: Points things
  removepoints:
    description: Points things
  setpoints:
    description: Points things
