name: RuralMC
main: com.ruralmc.plugin.RuralMC
version: 1.12.1.61-RELEASE
author: Chaka
depend: [WorldGuard]
commands:
  rmc:
    description: This is the main RMC command.
  claim:
    description: Claim a chunk
  points:
    description: Points things
  addpoints:
    description: Points things
  removepoints:
    description: Points things
  setpoints:
    description: Points things
